services:
  tv-thing:
    build: .
    container_name: tv-thing
    restart: unless-stopped
    ports:
      - '13339:3000'
    environment:
      - TL_USERNAME=${TL_USERNAME}
      - TL_PASSWORD=${TL_PASSWORD}
      - QB_URL=${QB_URL}
      - QB_USERNAME=${QB_USERNAME}
      - QB_PASSWORD=${QB_PASSWORD}
    volumes:
      - /home/aaron/homelab/data/media:/media
      - /home/aaron/homelab/data/torrents:/torrents:ro
